### PR TITLE
Workaround for Windows 8/8.1 and 10 notifications

### PR DESCRIPTION
**Pull request by mrbmi513**
Added setAppUserModelId statements to the Windows build. End user must add a shortcut to Start Menu folder. This workaround ended up working for me on another app, but I don't have enough friends using Allo to test this fix on this particular app. :)

### CODE REVIEW

**Comment by mrbmi513** [comment]
Update: The setting to Show notifications in action center was off by default in the windows Settings app. So they should stick with this setting on. 😄

**Comment by kelyvin** [comment]
Wow thanks a bunch for making all of these changes!!! I have merged your changes in and will include them in the release. 

Thanks!

**Comment by mrbmi513** [comment]
I don't know why git insists on saying there were 22 changes per file. I only added one line to each of those files, and it said I changed blank lines. Must be a Windows thing. Regardless, thanks for the kind words.

**Comment by AdrianoCahete** [comment]
> I don't know why git insists on saying there were 22 changes per file. I only added one line to each of those files, and it said I changed blank lines. Must be a Windows thing. Regardless, thanks for the kind words.


Your code editor might been stripping spaces on blank lines (VS Code, maybe?). It's good, 'cause it's cleaning the file. :P

**Pull request merged**
